package:
  name: deepchem
  version: {{ GIT_DESCRIBE_TAG }} 

source:
  path: ../../

build:
  number: 0
  skip:
    - [osx or win]


requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - networkx
    - tensorflow
    - keras
    - rdkit
    - joblib
    - pbr
    - h5py
    - dill
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - networkx
    - tensorflow
    - py-xgboost
    - keras
    - rdkit
    - mdtraj
    - pdbfixer
    - joblib
    - pbr
    - h5py
    - dill

test:
  requires:
    - nose
    - runipy

  imports:
    - deepchem

  commands:
    - nosetests -v deepchem

about:
  home: https://github.com/pandegroup/deepchem
  license: LGPLv2.1+
  summary: 'deepchem: Deep-learning models for drug discovery and quantum chemistry'
